**Array Creation**


Installing Numpy Using PIP 

In [11]:
!pip show Numpy
!pip install Numpy

  Using cached numpy-2.4.1-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.4.1-cp313-cp313-win_amd64.whl (12.3 MB)



[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


Importing numpy as np we use alias name of numpy as np

In [2]:
import numpy as np

Creating 0D array means Scalar

In [15]:
arr_0d =np.array(9)
arr_0d

array(9)

Creating one dimensional array means Vector 

In [14]:
arr_1d = np.array([1,2,3,4])
arr_1d

array([1, 2, 3, 4])

Creating 2D array means Matrices

In [3]:
arr_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Creating 3D arrays examples:-

In [17]:
arr_3D = np.array([[[1,2,3],[4,3,2]]])
arr_3D

array([[[1, 2, 3],
        [4, 3, 2]]])

**Creating Arrays with Different Methods with Different Formats**

*Creating Arrays with full of zero elements in array*

In [24]:
Zeroes_1D = np.zeros(3)  # 1D Vector
Zeroes_1D



array([0., 0., 0.])

In [25]:
Zeroes_2D =np.zeros((4,5))
Zeroes_2D

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
Zeroes_3D = np.zeros((3,3,3))
Zeroes_3D

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

*Creating array with full of 1 present in whole array as element*

We can also create 1D,2D,3D arrays as it as we createad in Zeroes Case

In [27]:
Ones = np.ones((3,3))
Ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

*Creating an array as we want desired elements in the array*
Also we can create it in different dimensions

In [28]:
Desired = np.full((3,3),7)
Desired

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In the above code we passes two things first the size of of the array and second is the number we want to full the array

*Creating with random elements in the whole array elements*

In [33]:
Random_arr = np.random.random((2,2))
Random_arr *= 10
Random_arr
#int(Random_arr)  # we can't do because only 0-dimensional arrays can be converted to Python scalars

array([[7.81112891, 6.1583731 ],
       [7.35388218, 7.55850313]])

*We creting array with the help of Sequence*

In [43]:
sequence = np.arange(0,10,2)
sequence

array([0, 2, 4, 6, 8])

**Finding Properties of Array**

In [44]:
arr = np.full((3,5),8)
arr

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [ ]:
print("Shape of the array:",arr.shape)   # first one for row and second for column

Shape of the array: (3, 5)


In [47]:
print("Dimension of the array:" ,arr.ndim)

Dimension of the array: 2


In [48]:
print("Size of the array:",arr.size)

Size of the array: 15


In [49]:
print("DataTypes of the array:",arr.dtype)

DataTypes of the array: int64


**Reshaping of the array**

In [9]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

*Now we are reshaping the arr into 1D to 2D using reshape function*
*in the below function we defining 4 rows and 3 columns matrix we passing two argumnets in reshape function*
*First is for row and second is for column in the tuple format* 

In [10]:
reshaped = arr.reshape((4,3))
reshaped

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

*Using the Flattened built in function we can arrange the array in the same rows means a vector*
*example is given below in thsi we defined matrix to vector (2D -> 1D)*

In [12]:
Flattened = reshaped.flatten()
Flattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

*Using the T function we can also tranpose the matrix means we can convert row into column and vice-versa.*

In [ ]:
Transpose = reshaped.T
Transpose

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

**ARRAY OPERATIONS**

***Array Slicing***

*We can get the certain part of an array using slicing function*
*Some examples are give for 1D , 2D ,ND arrays*

In [28]:
One_D =np.arange(9)
One_D

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
print("Basic Slicing of array:",One_D[3:7])

Basic Slicing of array: [3 4 5 6]


In [19]:
print("Basic Slicing of array:",One_D[2:])

Basic Slicing of array: [2 3 4 5 6]


In [20]:
print("Basic Slicing of array:",One_D[:4])

Basic Slicing of array: [0 1 2 3]


*In the above examples we can easily see that we can provide starting index and ending index(Exclusive) during the slicing if we not provide the starting index then it start from 0th index and if you not provide ending index then it goes till the length of the array*

In [21]:
print("Slicing with step:",One_D[0:6:2])

Slicing with step: [0 2 4]


*In the above example we slicing the array using step method in we passes three argument first for starting index and second for ending index and for step means how much we jump one element to another element* -----------We can also do negative index the example is given below 

In [ ]:
print("Negative Indexing:",One_D[-1])

Negative Indexing: [0 1 2 3 4 5]


*In the below examples we are learning different types of slicing 2D array*

In [30]:
Two_D = One_D.reshape((3,3))
Two_D

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
print("slicing for specific element:",Two_D[2,1])

slicing for specific element: 7


In [32]:
print("Slicing for entire row:",Two_D[0])

Slicing for entire row: [0 1 2]


In [37]:
print("Slicing for entire column:",Two_D[:,2])

Slicing for entire column: [2 5 8]


In [38]:
print("slicing for specific portion of matrix:",Two_D[1:3,1:3])

slicing for specific portion of matrix: [[4 5]
 [7 8]]


***Sorting in arrays***

In [42]:
unSorted =np.array([4,21,8,0,3,1,2,7])
unSorted

array([ 4, 21,  8,  0,  3,  1,  2,  7])

In [43]:
sorted = np.sort(unSorted)
sorted

array([ 0,  1,  2,  3,  4,  7,  8, 21])

In [45]:
unSorted_2D =unSorted.reshape((4,2))
unSorted_2D

array([[ 4, 21],
       [ 8,  0],
       [ 3,  1],
       [ 2,  7]])

*By default in 2D sorting perfform row was if we need to change this we have to give the axis= 1 or 0*-------------------*1 for row and 0 for column we can see the the given example*

In [46]:
sorted_2D = np.sort(unSorted_2D)
sorted_2D

array([[ 4, 21],
       [ 0,  8],
       [ 1,  3],
       [ 2,  7]])

In [48]:
sorted_2D = np.sort(unSorted_2D,axis=0)
sorted_2D

array([[ 2,  0],
       [ 3,  1],
       [ 4,  7],
       [ 8, 21]])

***Filter in the array***

In [49]:
unSorted

array([ 4, 21,  8,  0,  3,  1,  2,  7])

In [50]:
odd_numbers = unSorted[unSorted % 2 != 0]
odd_numbers

array([21,  3,  1,  7])

In [51]:
mask = unSorted < 20
print(unSorted[mask])

[4 8 0 3 1 2 7]


*In the above both examples we can filter our array to get the desired output using mask function or direct*

*In the below example we filtering the array with where method in this method we passes three things first conditio second if it true then do this and third if it false or must print this*

In [52]:
unSorted1 = np.where(unSorted < 6,unSorted *2,unSorted)
unSorted1

array([ 8, 21,  8,  0,  6,  2,  4,  7])

***Adding  Array***

In [54]:
a1 = np.array([8,5,3])
a2 = np.array([2,6,2])
print(a1,a2)
a3 = np.concatenate((a1,a2))
a3 

[8 5 3] [2 6 2]


array([8, 5, 3, 2, 6, 2])

***Array Compatibility***

In [55]:
print("Compatibility shape:", a1.shape == a2.shape )

Compatibility shape: True


***Removing Array***

In [56]:
a1

array([8, 5, 3])

In [59]:
deleted = np.delete(a1,0)
deleted

array([5, 3])

Some extra methods

In [61]:
average = np.mean(a1)
average

np.float64(5.333333333333333)

In [62]:
max = np.max(a1)
max

np.int64(8)

In [63]:
min = np.min(a1)
min

np.int64(3)

In [64]:
cumsum = np.cumsum(a1)
cumsum

array([ 8, 13, 16])

**We can also perform some Linear Algebric functions with array with the help of numpy**

In [7]:
al = np.arange(16)
print(al)
al1 = np.arange(1,33,2)
print(al1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31]


In [8]:
al2 =al.reshape((4,4))
print(al2)
al3 = al1.reshape((4,4))
print(al3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]]


In [ ]:
print(np.linalg.det((al3,al2)))

0.0


In [13]:
print(np.linalg.matrix_rank((al2,al3)))

[2 2]


In [15]:
print(np.linalg.solve(al2,al3))

LinAlgError: Singular matrix

In [18]:
print(np.linalg.inv(al3))

[[ 3.75299969e+14 -5.62949953e+14  0.00000000e+00  1.87649984e+14]
 [ 6.75539944e+15 -7.88129935e+15 -4.50359963e+15  5.62949953e+15]
 [-1.46366988e+16  1.74514486e+16  9.00719925e+15 -1.18219490e+16]
 [ 7.50599938e+15 -9.00719925e+15 -4.50359963e+15  6.00479950e+15]]


In [19]:
print(np.linalg.matrix_transpose(al2))

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [20]:
print(np.linalg.diagonal(al2))

[ 0  5 10 15]
